name       : libmypaint
version    : 1.3.0
release    : 5
source     :
    - https://github.com/mypaint/libmypaint/releases/download/v1.3.0/libmypaint-1.3.0.tar.xz : 6a07d9d57fea60f68d218a953ce91b168975a003db24de6ac01ad69dcc94a671
license    : ISC
component  : multimedia.library
summary    : A library for making brushstrokes
description: |
    libmypaint, a.k.a. "brushlib", is a library for making brushstrokes which is used by MyPaint and other projects.
builddeps  :
    - pkgconfig(gegl-0.4)
    - pkgconfig(json-c)
setup      : |
    %patch -p1 < $pkgfiles/gegl-0.4.patch

    %configure --disable-static \
        --enable-gegl
build      : |
    %make
install    : |
    %make_install
