name       : libmypaint
version    : 1.5.0
release    : 10
source     :
    - https://github.com/mypaint/libmypaint/releases/download/v1.5.0/libmypaint-1.5.0.tar.xz : aba6e0526f9e4bead4a89c7c82084971b90c5128b50da77b0ac0f5ef27772b57
license    : ISC
component  : multimedia.library
summary    : A library for making brushstrokes
description: |
    libmypaint, a.k.a. "brushlib", is a library for making brushstrokes which is used by MyPaint and other projects.
builddeps  :
    - pkgconfig(gegl-0.4)
    - pkgconfig(json-c)
environment: |
    # Upstream recommended CFLAGS
    export CFLAGS='-Ofast -ftree-vectorize -fopt-info-vec-optimized -funsafe-math-optimizations -funsafe-loop-optimizations'
setup      : |
    %configure --disable-static --enable-gegl
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
