name       : libmypaint
version    : 1.6.1
release    : 17
source     :
    - https://github.com/mypaint/libmypaint/releases/download/v1.6.1/libmypaint-1.6.1.tar.xz : 741754f293f6b7668f941506da07cd7725629a793108bb31633fb6c3eae5315f
license    : ISC
component  : multimedia.library
summary    : A library for making brushstrokes
description: |
    libmypaint, a.k.a. "brushlib", is a library for making brushstrokes which is used by MyPaint and other projects.
builddeps  :
    - pkgconfig(gegl-0.4)
    - pkgconfig(json-c)
environment: |
    # Upstream recommended CFLAGS
    export CFLAGS='-Ofast -ftree-vectorize -fopt-info-vec-optimized -funsafe-math-optimizations -funsafe-loop-optimizations'
setup      : |
    %configure --disable-static --enable-gegl
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
